### ISSUE TITLE
Support Selected Interface

### ISSUE THREAD

**Issue by py7hon** [vergoh/vnstat-docker#16]
Can you add the options **-i/-iface** for the selected interface ?

**Comment by vergoh** [comment]
Could you provide more details regarding (or an example of) the behaviour or use case you are looking for?

I'm not exactly sure yet what the missing feature is based on your request as `vnstat` in the container does expose `-i` / `--iface` to the command line.

**Comment by py7hon** [comment]
I mean like on `docker-compose.yml` having a Environment variables like `INTERFACE=eth0` 

```yml
version: "3.7"
services:

  vnstat:
    image: vergoh/vnstat:latest
    container_name: vnstat
    restart: unless-stopped
    network_mode: "host"
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - vnstatdb:/var/lib/vnstat
    environment:
      - HTTP_PORT=8685
      - INTERFACE=eth0 #like this
      - HTTP_BIND=*
      - HTTP_LOG=/dev/stdout
      - LARGE_FONTS=0
      - CACHE_TIME=1
      - RATE_UNIT=1
      - INTERFACE_ORDER=0
      - DARK_MODE=0
      - PAGE_REFRESH=0

volumes:
  vnstatdb:
  ```
