### ISSUE TITLE
Container has wrong time zone

### ISSUE THREAD

**Issue by goose-ws** [vergoh/vnstat-docker#6]
Using the `:latest` tag on Debian 10:

```
[goose@Vergil: /docker/config/vnstatdb ] $ docker inspect -f '{{ json .Mounts }}' vnstat | jq
[
  {
    "Type": "bind",
    "Source": "/etc/localtime",
    "Destination": "/etc/localtime",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  },
  {
    "Type": "bind",
    "Source": "/docker/config/vnstatdb",
    "Destination": "/var/lib/vnstat",
    "Mode": "rw",
    "RW": true,
    "Propagation": "rslave"
  },
  {
    "Type": "bind",
    "Source": "/etc/timezone",
    "Destination": "/etc/timezone",
    "Mode": "ro",
    "RW": false,
    "Propagation": "rprivate"
  }
]
[goose@Vergil: /docker/config/vnstatdb ] $ docker exec -it vnstat cat /etc/timezone /etc/localtime
America/New_York
TZif2▒▒▒▒p▒▒▒`▒▒p▒▒▒`▒e▒p▒▒▒▒j▒p▒5▒`▒S▒▒▒`▒3▒▒▒▒▒▒▒އ▒▒p▒i▒▒R▒K௳4▒~-౜Qp▒gJ`▒|3p▒G,`▒\p▒'`▒;▒p▒▒`▒p▒▒▒`▒▒▒ƴ`▒▒▒▒▒▒Ĺ𿏲▒▒▒▒▒▒o▒▒}@p▒▒9`ˈ▒p▒#▒p▒`▒▒▒u▒▒▒@▒▒▒U▒▒▒ ▒▒▒5▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒p▒▒e▒▒މpݩ▒`޾kp߉d`▒▒Mp▒iF`▒~/p▒I(`▒^p▒W.▒▒G-▒▒7▒▒'▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ֶ▒▒Ƶ▒▒▒`▒▒p▒`▒p▒▒`▒o▒p▒_y`▒Oxp▒?[`▒/Zp▒(w▒▒<pY▒▒▒X▒▒▒;▒▒▒:▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒w▒▒p▒``▒pP▒`@▒p0▒`▒p    ▒`      ▒▒▒
▒▒`
   ▒▒p
▒gp▒▒▒▒▒▒▒f▒▒e▒yH▒iG▒Y*▒I)▒9
                            ▒)
                              ▒")▒▒
                                   `▒
p▒`▒▒p▒▒`▒▒p▒▒` v▒!▒▒`"U▒▒#j▒▒$5▒▒%J▒▒&▒▒'*s▒'▒▒p)
xpeG/`e▒Zpg'`g▒<pi▒`i▒pj▒▒`k▒:▒l▒▒▒mv▒n▒▒▒oU▒▒p▒▒▒q5▒▒ro▒▒s▒▒tOy▒t▒▒pv8▒`v▒▒pxx`x▒▒py▒Z`z▒▒p{▒<`|~gp}▒`~^Ip▒`▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
                                                                                                                            ▒▒▒▒LMTEDTESTEWTEPTTZif2▒▒▒▒▒^▒▒▒▒▒▒▒p▒▒▒▒▒▒▒`▒▒▒▒▒▒p▒▒▒▒▒▒▒`▒▒▒▒▒e▒p▒▒▒▒▒▒▒▒▒▒▒▒▒j▒p▒▒▒▒▒5▒`▒▒▒▒▒S▒▒▒▒▒▒▒▒`▒▒▒▒▒3▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒އ▒▒▒▒▒▒▒p▒▒▒▒▒▒▒i▒▒▒▒▒▒▒R▒▒▒▒▒▒▒K▒▒▒▒▒▒▒4▒▒▒▒▒▒~-▒▒▒▒▒▒▒Qp▒▒▒▒▒gJ`▒▒▒▒▒|3p▒▒▒▒▒G,`▒▒▒▒▒\p▒▒▒▒▒'`▒▒▒▒▒;▒p▒▒▒▒▒▒`▒▒▒▒▒p▒▒▒▒▒▒▒`▒▒▒▒▒▒▒▒▒▒▒▒ƴ`▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒Ĺ▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒o▒▒▒▒▒▒}▒▒▒▒▒▒Ov▒▒▒▒▒▒d_▒▒▒▒▒▒/X▒▒▒▒▒▒M|p▒▒▒▒▒:▒▒▒▒▒▒-^p▒@p▒▒▒▒▒▒9`▒▒▒▒ˈ▒p▒▒▒▒▒#▒p▒▒▒▒▒`▒▒▒▒▒▒▒u▒▒▒▒▒▒▒@▒▒▒▒▒▒▒U▒▒▒▒▒▒▒ ▒▒▒▒▒▒▒5▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒p▒▒▒▒▒▒e▒▒▒▒▒▒މp▒▒▒▒ݩ▒`▒▒▒▒޾kp▒▒▒▒߉d`▒▒▒▒▒▒Mp▒▒▒▒▒iF`▒▒▒▒▒~/p▒▒▒▒▒I(`▒▒▒▒▒^p▒▒▒▒▒W.▒▒▒▒▒▒G-▒▒▒▒▒▒7▒▒▒▒▒▒'▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒ֶ▒▒▒▒▒▒Ƶ▒▒▒▒▒▒▒`▒▒▒▒▒▒p▒▒▒▒▒`▒▒▒▒▒p▒▒▒▒▒▒`▒▒▒▒▒o▒p▒▒▒▒▒_y`▒▒▒▒▒Oxp▒▒▒▒▒?[`▒▒▒▒▒/Zp▒▒▒▒▒(w▒▒▒▒▒▒<p▒▒▒▒Y▒▒▒▒▒▒▒X▒▒▒▒▒▒▒;▒▒▒▒▒▒▒:▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒w▒▒p▒``▒pP▒`@▒p0▒`▒p      ▒`      ▒▒▒
▒▒`
   ▒▒p
▒gp▒▒▒▒▒▒▒f▒▒e▒yH▒iG▒Y*▒I)▒9
                            ▒)
                              ▒")▒▒
                                   `▒
p▒`▒▒p▒▒`▒▒p▒▒` v▒!▒▒`"U▒▒#j▒▒$5▒▒%J▒▒&▒▒'*s▒'▒▒p)
xpeG/`e▒Zpg'`g▒<pi▒`i▒pj▒▒`k▒:▒l▒▒▒mv▒n▒▒▒oU▒▒p▒▒▒q5▒▒ro▒▒s▒▒tOy▒t▒▒pv8▒`v▒▒pxx`x▒▒py▒Z`z▒▒p{▒<`|~gp}▒`~^Ip▒`▒▒▒▒▒▒▒▒▒▒▒▒▒▒▒
                                                                                                                            ▒▒▒▒LMTEDTESTEWTEPT
EST5EDT,M3.2.0,M11.1.0
[goose@Vergil: /docker/config/vnstatdb ] $ docker exec -it vnstat date
Mon Feb  7 01:27:29 UTC 2022
[goose@Vergil: /docker/config/vnstatdb ] $
```

Not sure where my issue is, any ideas?

**Comment by vergoh** [comment]
I tried to figure out some way to replicate your situation based on that information but didn't succeed. The `docker inspect` ouput doesn't differ either for `/etc/timezone` and `/etc/localtime` if started with the example shown in the README.md.

Which docker command or docker-compose file content are you using to start the container?
Does the `date` command outside the container show the timezone correctly?

**Comment by goose-ws** [comment]
Here's the segment of the compose file I'm using:

```
  vnstat:
    container_name: vnstat
    hostname: vnstat
    image: vergoh/vnstat:latest
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/docker/config/vnstatdb:/var/lib/vnstat"
    environment:
      - "HTTP_PORT=0"
      - "TZ=America/New_York"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    network_mode: "host"

  vnstati:
    container_name: vnstati
    hostname: vnstati
    image: vergoh/vnstat:latest
    ports:
      - "8685:8685"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "/etc/timezone:/etc/timezone:ro"
      - "/docker/config/vnstatdb:/var/lib/vnstat:ro"
    environment:
      - "HTTP_PORT=8685"
      - "HTTP_LOG=/dev/stdout"
      - "LARGE_FONTS=0"
      - "CACHE_TIME=1"
      - "RATE_UNIT=1"
      - "PAGE_REFRESH=0"
      - "RUN_VNSTATD=0"
      - "TZ=America/New_York"
    restart: unless-stopped
    labels:
      - "com.ouroboros.enable=true"
    logging:
      driver: json-file
      options: 
        max-file: "3"
        max-size: "10M"
    network_mode: VergilNet
```

`date` is correct outside the container, just not inside:

```
[goose@Vergil: ~ ] $ date
Mon 07 Feb 2022 04:17:06 PM EST
[goose@Vergil: ~ ] $ docker exec -it vnstat date
Mon Feb  7 21:17:12 UTC 2022
[goose@Vergil: ~ ] $ docker exec -it vnstati date
Mon Feb  7 21:17:19 UTC 2022
[goose@Vergil: ~ ] $
```
